version: '3.8'

services:
  app:
    build:
      context: .
    expose:
      - 8501
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`app.traduka.eu`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"